// Generated by CoffeeScript 1.10.0

/*
TabCarousel
===========

A Chrome extension to automatically cycle through tabs.

Licensed under the GPL v2.  Source code is available at https://github.com/benjaminoakes/TabCarousel

@seealso http://code.google.com/chrome/extensions/background_pages.html
@author Benjamin Oakes <hello@benjaminoakes.com>, @benjaminoakes
 */

(function() {
  'use strict';
  var BackgroundController, Carousel, Options, OptionsController, TabCarousel, carousel, localStorage, ns, options, root,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  if (typeof require !== "undefined" && require !== null) {
    localStorage = require('localStorage');
  } else {
    localStorage = window.localStorage;
  }

  TabCarousel = {};

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.TabCarousel = TabCarousel;

  ns = TabCarousel;

  Options = (function() {
    function Options() {}

    Options.prototype.firstRun = function(value) {
      if (value) {
        return localStorage.firstRun = value;
      } else {
        return !localStorage.firstRun;
      }
    };

    Options.prototype.flipWait_ms = function(ms) {
      if (ms) {
        return localStorage.flipWait_ms = ms;
      } else {
        return localStorage.flipWait_ms || Options.defaults.flipWait_ms;
      }
    };

    Options.prototype.automaticStart = function(value) {
      if (1 === arguments.length) {
        return localStorage.automaticStart = !!value;
      } else {
        if (localStorage.automaticStart) {
          return JSON.parse(localStorage.automaticStart);
        }
      }
    };

    return Options;

  })();

  Options.defaults = {
    flipWait_ms: 15 * 1000,
    reloadWait_ms: 5 * 60 * 1000
  };

  root.Options = Options;

  options = new Options;

  OptionsController = (function() {
    function OptionsController(form) {
      this.form = form;
      this.form.flipWait_ms.value = options.flipWait_ms();
      this.form.automaticStart.checked = options.automaticStart();
      this.form.onsubmit = this.onsubmit;
    }

    OptionsController.prototype.onsubmit = function() {
      var status;
      status = document.getElementById('status');
      status.innerHTML = '';
      options.flipWait_ms(this.flipWait_ms.value);
      options.automaticStart(this.automaticStart.value);
      setTimeout(function() {
        status.innerHTML = 'Saved';
        return status.style.color = 'green';
      }, 100);
      return false;
    };

    return OptionsController;

  })();

  ns.OptionsController = OptionsController;

  Carousel = (function() {
    function Carousel() {
      this.lastReloads_ms = {};
    }

    Carousel.prototype.reload = function(tabId) {
      var lastReload_ms, now_ms;
      now_ms = Date.now();
      lastReload_ms = this.lastReloads_ms[tabId];
      if (!lastReload_ms || (now_ms - lastReload_ms >= Options.defaults.reloadWait_ms)) {
        chrome.tabs.get(tabId, (function(_this) {
          return function(t) {
            return chrome.tabs.update(tabId, {
              url: t.url
            });
          };
        })(this));
        return this.lastReloads_ms[tabId] = now_ms;
      }
    };

    Carousel.prototype.select = function(windowId, count) {
      return chrome.tabs.getAllInWindow(windowId, (function(_this) {
        return function(tabs) {
          var nextTab, tab;
          tab = tabs[count % tabs.length];
          nextTab = tabs[(count + 1) % tabs.length];
          chrome.tabs.update(tab.id, {
            selected: true
          });
          return _this.reload(nextTab.id);
        };
      })(this));
    };

    Carousel.prototype.start = function(ms) {
      var continuation, count, windowId;
      count = 0;
      windowId = void 0;
      if (!ms) {
        ms = options.flipWait_ms();
      }
      chrome.windows.getCurrent((function(_this) {
        return function(w) {
          return windowId = w.id;
        };
      })(this));
      chrome.browserAction.setIcon({
        path: 'images/icon_32_exp_1.75_stop_emblem.png'
      });
      chrome.browserAction.setTitle({
        title: 'Stop Carousel'
      });
      continuation = (function(_this) {
        return function() {
          _this.select(windowId, count);
          count += 1;
          return _this.lastTimeout = setTimeout(continuation, ms);
        };
      })(this);
      return continuation();
    };

    Carousel.prototype.running = function() {
      return !!this.lastTimeout;
    };

    Carousel.prototype.stop = function() {
      clearTimeout(this.lastTimeout);
      this.lastTimeout = void 0;
      chrome.browserAction.setIcon({
        path: 'images/icon_32.png'
      });
      return chrome.browserAction.setTitle({
        title: 'Start Carousel'
      });
    };

    return Carousel;

  })();

  carousel = new Carousel;

  BackgroundController = (function() {
    function BackgroundController() {
      this.click = bind(this.click, this);
    }

    BackgroundController.prototype.tutorialText = "First-Use Tutorial\n  \nTabCarousel is simple:  open tabs you want to monitor throughout the day, then click the toolbar icon.  To stop, click the icon again.\n  \nBy default, TabCarousel will flip through your tabs every " + (String(Options.defaults.flipWait_ms / 1000)) + " s, reloading them every " + (String(Options.defaults.reloadWait_ms / 1000 / 60)) + " min.  It's great on a unused display or TV.  Put Chrome in full-screen mode (F11, or cmd-shift-f on the Mac) and let it go.\n  \nIf you want to change how often TabCarousel flips through your tabs, right click on the toolbar icon and choose \"Options\".";

    BackgroundController.prototype.tutorial = function() {
      window.alert(this.tutorialText);
      return options.firstRun(Date.now());
    };

    BackgroundController.prototype.click = function() {
      if (options.firstRun()) {
        this.tutorial();
      }
      if (!carousel.running()) {
        return carousel.start();
      } else {
        return carousel.stop();
      }
    };

    BackgroundController.prototype.load = function() {
      chrome.browserAction.onClicked.addListener(this.click);
      chrome.browserAction.setTitle({
        title: 'Start Carousel'
      });
      if (options.automaticStart()) {
        return carousel.start();
      }
    };

    return BackgroundController;

  })();

  ns.BackgroundController = BackgroundController;

}).call(this);
